[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[build.env]
NIXPACKS_NODE_VERSION = "20"
DATABASE_URL = "file:/app/data/prod.db"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
DATABASE_URL = "file:/app/data/prod.db"
AUTH_SECRET = "weaweb_super_secret_key_8h3j2k1l9m0n4b5v6c7x8z"
AUTH_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
